modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "extendedae_plus"
displayURL="https://github.com/GaLicn/ExtendedAE_Plus"
issueTrackerURL = "https://github.com/GaLicn/ExtendedAE_Plus/issues"
version = "${mod_version}"
displayName = "ExtendedAE Plus"
credits = "C-H716 for Code Contribution"
authors = "GaLi,Hao_cen"
description = "Add more practical features and auxiliary operations to the Applied Energistics 2 mod."
logoFile = "extendedae_plus.png"

[[dependencies.extendedae_plus]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedae_plus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedae_plus]]
modId = "expatternprovider"
mandatory = true
versionRange = "[1.19-0.0.1-forge,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "extendedae_plus.mixins.json"
